# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: project-k8s-deployment
# spec:
#   replicas: 3 
#   selector:
#     matchLabels:
#       app: project-k8s
#   template:
#     metadata:
#       labels:
#         app: project-k8s
#     spec:
#       containers:
#       - name: project-k8s
#         image: 879381250162.dkr.ecr.us-east-1.amazonaws.com/super-project:latest
#         ports:
#         - containerPort: 8080  

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: project-k8s-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: project-k8s
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 8080 

#Below is the YAML used to create the staging environment

apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s-deployment
  namespace: staging
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: project-k8s
  template:
    metadata:
      labels:
        app: project-k8s
    spec:
      containers:
      - name: project-k8s
        image: 879381250162.dkr.ecr.us-east-1.amazonaws.com/super-project:latest
        ports:
        - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  name: project-k8s-service
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: project-k8s
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  

